/**
 * RSS Feed Builder
 *
 * Reads article databases and generates RSS/Atom/JSON feed files
 * for each configured feed source.
 */

import { Feed } from "feed";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DOCS_DIR = join(ROOT, "docs");

const SITE_URL = "https://znck.github.io/feeds";

const FEEDS = [
  {
    slug: "anthropic-engineering",
    dataFile: "articles.json",
    title: "Anthropic Engineering Blog",
    description:
      "Unofficial RSS feed for the Anthropic Engineering Blog. Automatically generated by crawling anthropic.com/engineering.",
    link: "https://www.anthropic.com/engineering",
    image: "https://www.anthropic.com/favicon.ico",
    favicon: "https://www.anthropic.com/favicon.ico",
    copyright:
      "Content copyright Anthropic. Feed generated by znck/rss-feeds.",
    author: {
      name: "Anthropic Engineering",
      link: "https://www.anthropic.com/engineering",
    },
  },
  {
    slug: "openai-research",
    dataFile: "openai-research.json",
    title: "OpenAI Research",
    description:
      "Unofficial RSS feed for the OpenAI Research Index. Automatically generated by crawling openai.com/research/index.",
    link: "https://openai.com/research/index/",
    image: "https://openai.com/favicon.ico",
    favicon: "https://openai.com/favicon.ico",
    copyright: "Content copyright OpenAI. Feed generated by znck/rss-feeds.",
    author: {
      name: "OpenAI Research",
      link: "https://openai.com/research/index/",
    },
  },
];

async function buildFeed(config) {
  const articlesPath = join(ROOT, "data", config.dataFile);
  const articles = JSON.parse(await readFile(articlesPath, "utf-8"));
  console.log(
    `Building ${config.slug} feed from ${articles.length} articles.`
  );

  const feed = new Feed({
    title: config.title,
    description: config.description,
    id: `${SITE_URL}/${config.slug}.xml`,
    link: config.link,
    language: "en",
    image: config.image,
    favicon: config.favicon,
    copyright: config.copyright,
    updated: new Date(),
    feedLinks: {
      rss2: `${SITE_URL}/${config.slug}.xml`,
      atom: `${SITE_URL}/${config.slug}.atom`,
    },
    author: config.author,
  });

  for (const article of articles) {
    feed.addItem({
      title: article.title,
      id: article.url,
      link: article.url,
      description: article.description || "",
      date: article.date
        ? new Date(article.date)
        : new Date(article.discoveredAt || Date.now()),
      ...(article.image && {
        image: article.image,
      }),
    });
  }

  await writeFile(join(DOCS_DIR, `${config.slug}.xml`), feed.rss2());
  console.log(`Written: ${config.slug}.xml (RSS 2.0)`);

  await writeFile(join(DOCS_DIR, `${config.slug}.atom`), feed.atom1());
  console.log(`Written: ${config.slug}.atom (Atom)`);

  await writeFile(join(DOCS_DIR, `${config.slug}.json`), feed.json1());
  console.log(`Written: ${config.slug}.json (JSON Feed)`);
}

async function main() {
  await mkdir(DOCS_DIR, { recursive: true });

  for (const config of FEEDS) {
    await buildFeed(config);
  }
}

main().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
