/**
 * RSS Feed Builder
 *
 * Reads the articles database and generates an RSS/Atom feed XML file
 * and updates the GitHub Pages site.
 */

import { Feed } from "feed";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ARTICLES_PATH = join(ROOT, "data", "articles.json");
const DOCS_DIR = join(ROOT, "docs");

const SITE_URL = "https://znck.github.io/feeds";

async function main() {
  await mkdir(DOCS_DIR, { recursive: true });

  const articles = JSON.parse(await readFile(ARTICLES_PATH, "utf-8"));
  console.log(`Building feed from ${articles.length} articles.`);

  const feed = new Feed({
    title: "Anthropic Engineering Blog",
    description:
      "Unofficial RSS feed for the Anthropic Engineering Blog. Automatically generated by crawling anthropic.com/engineering.",
    id: `${SITE_URL}/anthropic-engineering.xml`,
    link: "https://www.anthropic.com/engineering",
    language: "en",
    image: "https://www.anthropic.com/favicon.ico",
    favicon: "https://www.anthropic.com/favicon.ico",
    copyright: "Content copyright Anthropic. Feed generated by znck/rss-feeds.",
    updated: new Date(),
    feedLinks: {
      rss2: `${SITE_URL}/anthropic-engineering.xml`,
      atom: `${SITE_URL}/anthropic-engineering.atom`,
    },
    author: {
      name: "Anthropic Engineering",
      link: "https://www.anthropic.com/engineering",
    },
  });

  for (const article of articles) {
    feed.addItem({
      title: article.title,
      id: article.url,
      link: article.url,
      description: article.description || "",
      date: article.date ? new Date(article.date) : new Date(article.discoveredAt || Date.now()),
      ...(article.image && {
        image: article.image,
      }),
    });
  }

  // Write RSS 2.0
  await writeFile(join(DOCS_DIR, "anthropic-engineering.xml"), feed.rss2());
  console.log("Written: anthropic-engineering.xml (RSS 2.0)");

  // Write Atom
  await writeFile(join(DOCS_DIR, "anthropic-engineering.atom"), feed.atom1());
  console.log("Written: anthropic-engineering.atom (Atom)");

  // Write JSON Feed
  await writeFile(join(DOCS_DIR, "anthropic-engineering.json"), feed.json1());
  console.log("Written: anthropic-engineering.json (JSON Feed)");
}

main().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
